### ISSUE TITLE
docs: Roadmap Item: Developer Tools, Like Redux Dev Tools

### ISSUE THREAD

**Issue by chonghorizons** [felangel/bloc#3073]
**Description**

This is just an update/ current state for someone that might take up this task later.
On https://github.com/felangel/bloc/wiki/Roadmap, this is written as

> Developer Tools
>  .  Like Redux Dev Tools but for bloc/cubit

### Short Version
- A simple version would take about 2-20 hours, but not much gain over custom `BlocObserver`.
- A complex version may not be technically feasible, especially the Redux "time travel" feature.

### Details
Works/Done
- [x] Reviewed https://github.com/andrea689/flutter_bloc_devtools, which wires up BlocObserver to emit commands to a Redux Dev Tools observer.
- [x] Updated that package for v8.0.0 of bloc. See https://github.com/chonghorizons/flutter_bloc_devtools. Very quick and dirty.
- [x] Confirmed working for a basic counter app, for `flutter build web`
- [x] Basic events and states reporting works. Essentially "read" mode.
- [x] Got the devtool server to work with the v8 flutter_todos tutorial (specifically, this [commit/version](https://github.com/chonghorizons/bloc/commit/42901785deadcc73076ffc82595b825edd205a5c). Didn't clean up the example.

Doesn't work
- [ ] Issues with converting the `state` to JSON so that it can display the state tree correctly. Namely, the state needs to support `toJSON()`.
- [ ] Some issues with Enum's and using  `jsonEncode()` See https://github.com/dart-lang/sdk/pull/47875/files
- [ ] Undo not implemented.
- [ ] Unsure if undo is even possible: how to send the command from the DevTool to the built instance to enable an undo. AKA "write" mode.
- [ ] Manual testing for `flutter build` to an apk.
- [ ] Writing unit tests for the package.

Recommendation:
- A basic "read" version of the DevTool that is robust could be done with minimal additional effort. (Maybe 2-20 hours).
- The package will display state as `toString()` if it can't `jsonEncode()`.
- Not sure if there is much gain over just using a custom `BlocObserver` to log events and the FlutterDevtools to view the console or look at the widget tree.
- A "read+write" version that allows one to set the state (e.g. do an Undo or "time travel") on the device running would be cool. But I'm not even sure how to implement that.

**Comment by felangel** [comment]
Thanks @chonghorizons for taking the time to put this together. Thoughts on consolidating this with #2748?

**Comment by chonghorizons** [comment]
Yes, consolidate!

**Comment by felangel** [comment]
Awesome, moved your comments over to #2748 👍
